AllCops:
  NewCops: enable
  Exclude:
    - "*/*_test.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 30

Style/GlobalVars:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Max: 30
